### ISSUE TITLE
Use Twig as template engine

### ISSUE THREAD

**Issue by sergix44** [popphp/popphp-framework#1]
It's possible to register a Twig instance as template engine?
Thanks

**Comment by nicksagona** [comment]
I wouldn't see why not. The pop-view is usually set up in an application that uses the Pop PHP Framework as the default view/template engine, but I wouldn't see why Twig couldn't be set up instead. I don't have a specific example of using Twig, per se, but if you look at the controller class in the tutorial application, you can see how the view is set up and rendered. I could see replacing that with Twig I would think? https://github.com/popphp/popphp-tutorial/blob/master/app/src/Controller/IndexController.php

**Comment by nicksagona** [comment]
If this answer satisfies the question, I'm going to close it out. Thanks.
