### ISSUE TITLE
Wrong path to the kettle application, when installing it in a standalone way, and adding it to the main folder

### ISSUE THREAD

**Issue by ghost** [popphp/popphp-framework#3]
Hi, and thanks for a great framework :-)

I've installed kettle with the command 'composer require popphp/pop-kettle', in a standalone way, and copied the kettle application to the main directory (as you mentioned in the docs in this repo), but didn't get it to work without updating the path to the "app.console.php" file from this:

`$app = new Pop\Application($autoloader, include __DIR__ . '/config/app.console.php');`

to this:

`$app = new Pop\Application($autoloader, include __DIR__ . '/vendor/popphp/pop-kettle/config/app.console.php');`

on line 10 in the 'main folder/kettle' file

Thought I should write you a line and mention it, so you can update the docs for others that might get stuck with the same issue like I did. Even if it's kind of logical that it behave this way when creating a copy of it :-)

Have a nice day!

**Comment by nicksagona** [comment]
Yes - you're correct. Missed that part in the README. It's been corrected. Thanks for your interest in Pop!
