### ISSUE TITLE
Will not boot on PHP 8

### ISSUE THREAD

**Issue by mattfletcher** [popphp/popphp-framework#4]
PHP Fatal error:  Uncaught Error: Unknown named parameter $application in [...]/project-folder/vendor/popphp/pop-utils/src/CallableObject.php:162

matt@dev:~/project-folder$ php -v
PHP 8.0.12 (cli) (built: Oct 22 2021 12:34:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.12, Copyright (c), by Zend Technologies

**Comment by nicksagona** [comment]
Thanks - I'll look into it. Which command were you running when you hit that? Something through kettle?

**Comment by mattfletcher** [comment]
kettle serve

**Comment by nicksagona** [comment]
So kettle serve by itself is just a extension of the php local web server command. Did you create a set of application classes, events and/or services to run a web app and are trying to test it/run it via kettle serve? Are you able to share any of that code?

**Comment by nicksagona** [comment]
Ok figured it out. It's an issue with named parameters in PHP 8 when calling `call_user_func_array` in a couple of places. It's been patched. If you update and get the new versions of `popphp` (3.7.1) and `pop-utils` (1.2.1) you should be good to go.
